/* eslint-disable */
// AUTO-GENERATED BY @dex/pie. DO NOT EDIT.
// Title: Concord API
// Version: 1.0.0
// Generated at: 2026-09-27T18:18:44.629Z

import { createPie, type PieOptions, type PieResponse } from '@dex/pie'

export interface Comment {
  author?: Record<string, any>
  content: string
  edited_at?: string
  id: string
  inserted_at: string
  parent_comment_id?: string
  post_id: string
}

export interface ContextualIdentityRequest {
  avatar_url?: string
  display_name?: string
  is_anonymous?: boolean
  tag?: string
}

export interface CreateCommentRequest {
  content: string
  parent_comment_id?: string
}

export interface CreateMessageRequest {
  content: string
  reply_to_id?: string
  type?: "text" | "file" | "media" | "system"
}

export interface CreatePostRequest {
  body: string
  echo_policy?: "space_only" | "realm_only" | "universal"
  title: string
}

export interface CreateRealmRequest {
  banner_url?: string
  description?: string
  icon_url?: string
  name: string
  rules_checklist?: (Record<string, any>)[]
  slug: string
  visibility?: "public" | "unlisted" | "private"
}

export interface CreateSpaceRequest {
  description?: string
  echo_policy?: "space_only" | "realm_only" | "universal"
  enabled_views?: string[]
  icon_url?: string
  kind?: "direct" | "group" | "community" | "organization"
  name: string
  realm_id?: string
  slug: string
  visibility?: "public" | "unlisted" | "private" | "direct"
}

export interface CreateUserRequest {
  avatar_url?: string
  bio?: string
  display_name: string
  email: string
  username: string
}

export interface FileAsset {
  content_type: string
  filename: string
  id: string
  inserted_at?: string
  metadata?: Record<string, any>
  preview_url?: string
  size_bytes: number
  space_id: string
  uploader?: Record<string, any>
  url: string
}

export interface Message {
  author?: Record<string, any>
  content: string
  deleted_at?: string
  edited_at?: string
  id: string
  inserted_at: string
  reactions?: (Record<string, any>)[]
  reply_to_id?: string
  space_id: string
  type: "text" | "file" | "media" | "system"
}

export interface Post {
  author?: Record<string, any>
  body: string
  comment_count?: number
  echo_count?: number
  echo_policy?: "space_only" | "realm_only" | "universal"
  echo_source_space_id?: string
  edited_at?: string
  id: string
  inserted_at?: string
  original_post_id?: string
  published_at: string
  space_id: string
  title: string
}

export interface Realm {
  banner_url?: string
  description?: string
  icon_url?: string
  id: string
  inserted_at?: string
  name: string
  rules_checklist?: (Record<string, any>)[]
  slug: string
  visibility: "public" | "unlisted" | "private"
}

export interface Space {
  description?: string
  echo_policy: "space_only" | "realm_only" | "universal"
  enabled_views: string[]
  icon_url?: string
  id: string
  inserted_at?: string
  kind: "direct" | "group" | "community" | "organization"
  name: string
  realm_agreed_rules?: string[]
  realm_agreement_status?: "none" | "pending" | "agreed" | "rejected"
  realm_id?: string
  slug: string
  visibility: "public" | "unlisted" | "private" | "direct"
}

export interface User {
  avatar_url?: string
  bio?: string
  display_name: string
  id: string
  inserted_at?: string
  username: string
}


/**
 * Navigable Route Tree Contract generated from OpenAPI.
 */
export type ApiRoutes = {
  v1: {
    messages: {
      (id: string | number | { id: string | number }): {
        reactions: {
          post: (options?: { body: {
  emoji: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
          delete: (options?: { query?: { emoji: string }; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
        }
      }
    }
    posts: {
      (id: string | number | { id: string | number }): {
        echo: {
          post: (options?: { body: {
  destination_space_id: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Post, Record<string, any>>>
        }
        comments: {
          get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Comment[], unknown>>
          post: (options?: { body: CreateCommentRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Comment, unknown>>
        }
        get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Post, Record<string, any>>>
      }
    }
    realms: {
      (id: string | number | { id: string | number }): {
        admit: {
          post: (options?: { body: {
  user_id: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
        }
        join: {
          post: (options?: { body: {
  user_id: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
        }
        spaces: {
          (space_id: string | number | { space_id: string | number }): {
            "agree-rules": {
              post: (options?: { body: {
  agreed_rules: string[]
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Space, unknown>>
            }
          }
          post: (options?: { body: {
  space_id: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Space, unknown>>
        }
        get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Realm, Record<string, any>>>
      }
      get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Realm[], unknown>>
      post: (options?: { body: CreateRealmRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Realm, Record<string, any>>>
    }
    spaces: {
      (id: string | number | { id: string | number }): {
        identity: {
          put: (options?: { body: ContextualIdentityRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
        }
        join: {
          post: (options?: { body: {
  tag?: string
  user_id: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Record<string, any>, unknown>>
        }
        files: {
          get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<FileAsset[], unknown>>
          post: (options?: { body: {
  content_type: string
  filename: string
  metadata?: Record<string, any>
  preview_url?: string
  size_bytes: number
  url: string
}; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<FileAsset, Record<string, any>>>
        }
        media: {
          get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<FileAsset[], unknown>>
        }
        messages: {
          get: (options?: { query?: { before?: string; after?: string; limit?: number }; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Message[], unknown>>
          post: (options?: { body: CreateMessageRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Message, Record<string, any>>>
        }
        posts: {
          get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Post[], unknown>>
          post: (options?: { body: CreatePostRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Post, Record<string, any>>>
        }
        get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Space, Record<string, any>>>
      }
      get: (options?: { query?: { realm_id?: string }; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Space[], unknown>>
      post: (options?: { body: CreateSpaceRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<Space, Record<string, any>>>
    }
    users: {
      "by-username": {
        (username: string | number | { username: string | number }): {
          get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<User, Record<string, any>>>
        }
      }
      (id: string | number | { id: string | number }): {
        get: (options?: { headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<User, Record<string, any>>>
      }
      post: (options?: { body: CreateUserRequest; headers?: Record<string, string>; baseUrl?: string; signal?: AbortSignal }) => Promise<PieResponse<User, Record<string, any>>>
    }
  }
}

/**
 * Preconfigured API client factory for this OpenAPI schema.
 */
export function createApiClient(options?: Partial<PieOptions>) {
  return createPie<ApiRoutes>({
    prefix: "/api",
    baseUrl: "http://localhost:4000",
    ...options,
  })
}
